version: '3.4'

services:
  blogservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    networks:
      - blogservicenetwork
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
    - blogservicenetwork

networks:
  blogservicenetwork:
    driver: bridge