using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace BlogService.Models
{
    public class Comment
    {
        public string Body { get; set; } = string.Empty;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime CreatedOn { get; set; } = DateTime.Now;

        public string Email { get; set; } = string.Empty;

        public string FirstName { get; set; } = string.Empty;

        //external Id
        public string Id { get; set; }

        //generated by MongoDb
        public ObjectId InternalId { get; set; }

        public string LastName { get; set; } = string.Empty;

        public string PostId { get; set; }

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;

        public string Website { get; set; } = string.Empty;
    }
}