using System;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace BlogService.DataModels
{
    public class Post
    {
        public string Body { get; set; } = string.Empty;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime CreatedOn { get; set; } = DateTime.Now;


        public HeaderImage Header { get; set; } = new HeaderImage();

        //external Id
        public string Id { get; set; }

        [BsonId]

        //generated by MongoDb
        public ObjectId InternalId { get; set; }

        public List<string> Tags { get; set; } = new List<string>();

        public string Title { get; set; } = string.Empty;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
    }
}